site_name: Build An Agent
site_description: AI Agent Development Workshop - Learn to build intelligent AI agents with LLMs and tools
site_author: Build An Agent Hackathon
site_url: https://stanchpillow55.github.io/build-an-agent/

repo_name: StanchPillow55/build-an-agent
repo_url: https://github.com/StanchPillow55/build-an-agent
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [code]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_category_heading: true
            members_order: source
            merge_init_into_class: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Usage Guide: usage.md
  - API Reference: api.md
  - Examples:
    - Curriculum Planning: examples/curriculum.md
    - PowerPoint Generation: examples/powerpoint.md
    - Content Sanitization: examples/sanitizer.md
